spring:
  thymeleaf:
    prefix: classpath:/templates
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    cache: false
  datasource:
    url: jdbc:mysql:///seckill?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  application:
    name: skill-demo
  redis:
    host: localhost
    password:
mybatis:
  configuration:
    map-underscore-to-camel-case: true